version: "3"
services:
  test:
    build: .
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    command: python python.py
    depends_on:
      - postgres
  postgres:
    container_name: postgres_app_2
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
